# Site settings
title: Ion
email: jianwengs@163.com
description: > # this means to ignore newlines until "baseurl:"
 试着做一些看似困难的事，试着放弃一些看似重要的物。
baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "https://314009053.github.io/" # the base hostname & protocol for your site

github_username:  314009053

# Build settings
markdown: kramdown
